name: Module6Task2

on:
  workflow_dispatch:
    inputs:
      custom-text:
        description: 'Enter the text to output'
        required: true
        default: 'Hello from input!'


jobs:
  Part1:
    runs-on: ubuntu-latest
    environment: prod  
    outputs:
      my-output: ${{ steps.set-output.outputs.text }}
    steps:
      - name: Set user input as output
        id: set-output
        run: echo "text=${{ github.event.inputs.custom-text }}" >> $GITHUB_OUTPUT

      - name: Echo environment secret and variable
        run: |
          echo "Secret Password: ${{ secrets.MY_SECRET }}"
          echo "Variable Code: ${{ vars.MY_VARIABLE }}"
